name: flync
description: "A flutter file synchronization app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  dartx: ^1.2.0
  device_preview: ^1.2.0
  ellipsized_text: ^2.0.0
  file_picker: ^10.0.0
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  ftpconnect: ^2.0.7
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  intl: ^0.19.0
  humanizer: ^3.0.0
  material_symbols_icons: ^4.2811.0
  animations: ^2.0.11
  go_router: ^14.8.1
  get_it: ^8.0.3
  dynamic_system_colors: ^1.8.0 #https://github.com/material-foundation/flutter-packages/issues/574#issuecomment-2636066025
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  flutter_slidable: ^4.0.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
